### PR TITLE
Create Georgian

### PR DESCRIPTION
**Pull request by BPG-InfoTech**
[https://bpgfonts.wordpress.com/2017/12/30/bpg-ssp/](url)
Georgian for SourceSansPro-Regular

### CODE REVIEW

**Comment by BPG-InfoTech** [comment]
[BPG SSP.zip](https://github.com/adobe-fonts/source-sans-pro/files/1594034/BPG.SSP.zip)

**Comment by BPG-InfoTech** [comment]
And, I do not know how to use instruments for this site… I can only work with TTF and OTF files…

**Comment by BPG-InfoTech** [comment]
Capitals are added
bpg ssp

**Comment by pauldhunt** [comment]
Hello @BPG-InfoTech 
Thank you for your interest in this project. Unfortunately, we cannot accept this work for a couple reasons:
- It is not in the proper format. We only accept design work in UFO format.
- The design is of a predetermined medium weight. We require designs to be compatible with the ExtraLight and Black masters.
Additionally, I notice that the design is not harmonized with the Source Sans design in terms of detailing including curve handling and terminal endings. If you would like to work with us to rectify these issues, please respond and let’s develop a strategy to create a Georgian addition for Source Sans that we can all be happy with.

**Comment by BPG-InfoTech** [comment]
pauldhunt

- on this stage format is not a problem and UFO can be used if we can have agreement on harmonization problems
- ExtraLight and Black masters also is not a problem, they can be done

At this stage harmonization is a problem, because original font not includes glyphs having important elements Georgian needs. And, I think harmonization is better to do with Normal/Regular font...

Basics for harmonization i have found are following:

1. Latin "o" as most important element for georgian glyphs = "eye": I have done it proportionally smaller then Latin to fit more complex high ascenders and complex lower descenders of Georgian:
o-circles
 
2. Connection of ovale to vertical lines can be used from "d" and "h"
bd

3. I have used Greek "ω" as a basement
or

4. I have used Cyrillic "з" for connections
vkpf

5. And I have used Greek "φ" for important "leg"'s upgoing part
evk

**Comment by BPG-InfoTech** [comment]
Actually most Georgian glyphs are complex as Latin "g" in original font. And lines of "g" are not typical to other glyphs in orgiginal font...
go

**Comment by pauldhunt** [comment]
@BPG-InfoTech Thanks for the additional info. I am seeing some things that I would like to change. Let me set up a separate project for Georgian and let’s collaborate on a design we can all be happy with. I will do a small set of glyphs and then you can review what you think I have done right and what you think I have missed. Please give me a few weeks to complete this and then we can see how we would like to proceed.

**Comment by BPG-InfoTech** [comment]
@pauldhunt I agree this way. 
And here is TTF of my draft:
[01 BPG_SSP.zip](https://github.com/adobe-fonts/source-sans-pro/files/1642033/01.BPG_SSP.zip)

**Comment by BPG-InfoTech** [comment]
Here are "native", "standard" shapes and proportions of Georgian letters all Georgians study in the first class of the school and remember during all their life.
font_dedaena

**Pull request closed without merging**
