### PR TITLE
Bulg cyr

### PR DESCRIPTION
**Pull request by StefanPeev**
@miguelsousa Is it now OK everything?

### CODE REVIEW

**Comment by miguelsousa** [comment]
@StefanPeev nope. There are 24 commits in this PR. I asked for one only.

**Comment by StefanPeev** [comment]
@miguelsousa I'm sorry. I've deleted all this stuff (or I hope I did it...) except the latest changes and I can't understand why they are again here.

**Comment by StefanPeev** [comment]
@miguelsousa I want to PR only 2 files SourceSans_ExtraLight.ufo and SourceSans_Black.ufo.

**Comment by miguelsousa** [comment]
I understand what you want to do, but I have no idea how you're doing it. I'm sorry to say that this PR looks a mess right now. I can't do anything on my end until you fix things on your end.

**Comment by frankrolf** [comment]
Alternatively, you could also open a new, clean PR with a single commit and close this one.

**Comment by Manuel-K** [comment]
> Alternatively, you could also open a new, clean PR with a single commit and close this one.

That will not help if he creates the new branch based of his master branch.

@StefanPeev The easiest way to fix this would be:
1. Make a copy of your `Roman` folder somewhere safe.
2. Clean your master branch by using by doing a hard reset to @miguelsousa's last commit (e.g. `git reset --hard d975556bf929ede3066c128367e26d0a0d8c7705` for the command line client.
You can then either
3a. Clean up your `bulg-cyr` by doing a hard reset to your master – or
3b. Create a new branch off your master branch.
4. Copy your saved `Roman` folder back into the repo.
5. Create a clean commit.
6a. if you've done 3a) you have to do a force push (e.g. `git push --force`) of the bulg-cyr branch.

**Comment by Manuel-K** [comment]
Alternatively you can do a interactive rebase and squash the commits.

**Comment by Manuel-K** [comment]
But you should definitely clear your master branch.

**Comment by StefanPeev** [comment]
@miguelsousa @frankrolf @Manuel-K Thank you for your patience! I started a clean PR #137.

**Pull request closed without merging**
