### PR TITLE
Bulgarian Cyrillic letter form model

### PR DESCRIPTION
**Pull request by StefanPeev**
@miguelsousa I reverted everything to the beginnig and started a clean commitment.

### CODE REVIEW

**Comment by miguelsousa** [comment]
@StefanPeev much better. But these UFOs are not normalized. Please normalize, amend the commit, and force push.

**Comment by StefanPeev** [comment]
@miguelsousa I'm sorry, Muguel... It was such a great effort to find a solution with the commitments, that I forgot to normalize the UFOs...

**Comment by StefanPeev** [comment]
@miguelsousa Is it OK or to start again from the beginning, Miguel?

**Comment by miguelsousa** [comment]
@StefanPeev I'm not sure. It looks OK on the surface. I'm going to merge it and massage the files. If I need anything I'll let you know. Thanks

**Comment by miguelsousa** [comment]
@pauldhunt the branch `bulg-cyr` has Stefan's changes. Please have a look.

**Pull request merged**
