### PR TITLE
Modern form of Bulgarian Cyrillic

### PR DESCRIPTION
**Pull request by StefanPeev**
Support for modern form of Bulgarian Cyrillic by .loclBGR

### CODE REVIEW

**Comment by pauldhunt** [comment]
Hello @StefanPeev
Thank you for your interest in this project. Unfortunately, we cannot accept this work for a couple reasons:

- It is not in the proper format. We only accept design work in UFO format.
- The design is only of the Black weight. We require designs to be compatible with the ExtraLight and Black masters.

If you would like to work with us to rectify these issues, please respond and let’s develop a strategy to create a Georgian addition for Source Sans that we can all be happy with.

**Comment by StefanPeev** [comment]
Thank you for the answer @pauldhunt.
I could offer you my proposals in UFO format both for Black and ExtraLight weights.

**Comment by pauldhunt** [comment]
This sounds like a good starting point. Let’s do that and go from there. Thanks!

**Comment by StefanPeev** [comment]
Thank you @pauldhunt. I'll prepare my proposal and will make a PR, when I'm ready.

**Pull request closed without merging**
