### PR TITLE
Bulgarian Cyrillic Local Forms

### PR DESCRIPTION
**Pull request by StefanPeev**
It is a proposal for Bulgarian Cyrillic Local Forms.

### CODE REVIEW

**Comment by StefanPeev** [comment]
@pauldhunt @miguelsousa Please, consider my proposal for Bulgarian Cyrillic Local Forms.

**Comment by miguelsousa** [comment]
@StefanPeev please normalize the UFOs with [ufonormalizer](https://github.com/unified-font-object/ufoNormalizer) to reduce the amount of changes. Make sure you use the `-m` option.

**Comment by StefanPeev** [comment]
@miguelsousa Sorry, but where could I get more information for the normalization rules and ufonormalizer usage?

**Comment by StefanPeev** [comment]
@miguelsousa Is it OK now?

**Comment by miguelsousa** [comment]
@StefanPeev no. It seams that you've created a new folder named **Cyrillic** and put new UFOs there. Instead of creating new UFOs, make your proposed changes directly to the current UFOs.

The commits also include a file named **SourceSansPro-Black.ufo.zip**. What is it?

**Comment by StefanPeev** [comment]
@miguelsousa I'm sorry! SourceSansPro-Black.ufo.zip is a very old version - the one which I showed to Paul D. Hunt a year before. I'll delete the folder Cyrillic and its content.

**Comment by miguelsousa** [comment]
@StefanPeev it looks a lot better. What font editor did you use? Glyphs? There are a ton of changes to the color assigned to glyphs (`0.5470588235` -> `0.547059`). I can clean that up but first please reduce all of your commits to a single one.

**Comment by StefanPeev** [comment]
@miguelsousa I use FontForge. Open UFO's with FontForge and generate UFO's font when I'm done.

**Comment by miguelsousa** [comment]
Good to know. Thanks.

**Comment by StefanPeev** [comment]
@miguelsousa So, what else must I do?

**Comment by miguelsousa** [comment]
@StefanPeev Make one single commit with all these changes, and force-push it to your master.

**Comment by StefanPeev** [comment]
@miguelsousa OK, I'll try to do that but I have another question. I worked on SourceSans_ExtraLight.ufo and on SourceSans_Black.ufo but I haven't write a local feature for substition of international Cyrillic glyphs with the local Bulgarian Cyrillic glyphs in the UFO-s. I could submit separately a FEA file with the correct substutions for importing lately. So the question is whether I send a separate FEA file or just add the local feature for Bulgarian letter forms in the UFO-s?

**Comment by miguelsousa** [comment]
Just submit the changes to the UFO fonts. We can take care of the other changes.

**Comment by miguelsousa** [comment]
@StefanPeev I'm actually going to close this PR. I've created a new branch called `bulg-cyr`. When you open a new PR, please select `bulg-cyr` instead of `master`.

**Pull request closed without merging**
